
spring:
  application:
    name: config-client # 应用名称
  cloud:
    config:
      uri: http://localhost:8888    # 配置中心的地址
      name: application.yml         # 要读取的配置文件的名字
      label: master                # 分支名称
      profile: dev                 # 配置文件的级别
server:
  port: 8889                      # 服务的端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
    register-with-eureka: true