eureka:
  client:
    serviceUrl:
#      单机注册中心
#      defaultZone: http://localhost:8761/eureka
#      集群注册中心
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true                      #显示服务IP
    instance-id: feighTest-client-8765      # 服务名称
server:
  port: 8765
spring:
  application:
    name: feighTest-client-8765
feign:
  hystrix:
    enabled: true # 开启feigh的熔断器 feigh自带熔断器

info:   #注册中心 info信息填写，方便别人调用。
  app.name: testProduct
  company.name: 北京测试公司SpringCloud-forTest
  build.artifactId: $project.artifactId$
  build.version: $project.version$

ribbon:
  eureka:
    enabled: true